Repository dotansimha/graphql-eslint, pull requests merged in 2021-06, with the labels that each got.

#451 🎉 New rule `no-unused-fields`
  .changeset/mean-lies-invite.md
  docs/README.md
  docs/rules/no-unused-fields.md
  packages/plugin/src/graphql-ast.ts
  packages/plugin/src/parser.ts
  packages/plugin/src/rules/index.ts
  packages/plugin/src/rules/no-unused-fields.ts
  packages/plugin/src/types.ts
  packages/plugin/src/utils.ts
  packages/plugin/tests/no-unused-fields.spec.ts
Labels: new-rule

#491 Update README on the VSCode integration
  README.md
Labels: kind/docs

#441 🎉 New feature: Support `#import` for `known-fragment-names` rule
  .changeset/dry-vans-smile.md
  docs/rules/known-fragment-names.md
  packages/plugin/src/parser.ts
  packages/plugin/src/rules/graphql-js-validation.ts
  packages/plugin/src/sibling-operations.ts
  packages/plugin/tests/known-fragment-names.spec.ts
  packages/plugin/tests/mocks/user-fields.graphql
  packages/plugin/tests/mocks/user.graphql
Labels: kind/enhancement
